### PR TITLE
JUnit xml report generation was fixed.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Previously, pytest_runtest_logreport hook was called inside forked
processed, and main pytest process wasn't able to know about the test
results.

This fix uses a separate multiprocessing Queue to pass results back
to the main process.

This pull fixed issue https://github.com/browsertron/pytest-parallel/issues/24

### CODE REVIEW

**Comment by kevlened** [comment]
Whoa. This is great. It's a substantial change to core logic, so I'd like to review more and test some things, then I'll release a major version rev.

**Comment by svetlyak40wt** [comment]
Sure, I already using these changes in my company's production pipeline on TeamCity.

**Comment by svetlyak40wt** [comment]
Yes! This is great!

Thank you, @kevlened!

**Comment by kevlened** [comment]
No, thank you! Your changes are deployed to [PyPI as 0.1.0](https://pypi.org/project/pytest-parallel/0.1.0/)

**Pull request merged**
