### PR TITLE
[WIP] ci: report coverage via codecov

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/browsertron/pytest-parallel/issues/56.

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, Travis created two "Travis CI - Pull Request" builds?

@kevlened 
Did you change some config in this regard?

**Comment by kevlened** [comment]
I haven't changed anything. I'm not sure how that happened.

**Comment by blueyed** [comment]
ok, fine with a rebuild, so likely a hiccup on their end.

**Comment by blueyed** [comment]
@kevlened 
Thanks for merging, but I wanted to look at it more closely (therefore "[WIP]").
Anyway, not too bad - and at least we have a base report then to follow up upon.. :)

**Comment by kevlened** [comment]
Sorry, jumped the gun. Just excited.

**Comment by blueyed** [comment]
> Sorry, jumped the gun. Just excited.

Fair enough.. :)

**Comment by blueyed** [comment]
I'm glad you're doing squash-merges in the first place, but you can also edit them (e.g. to not include "[WIP]" or "rebuild" in there).  JFI, thanks for being pro-active!

**Pull request merged**
