### PR TITLE
Fixes browsertron/pytest-parallel/#118

### PR DESCRIPTION
**Pull request by jfennick**
#118 is breaking many organizations' CI systems, including mine. Please merge asap.

### CODE REVIEW

**Review by WP-LKL — APPROVED** [review]
Also solved it for us.

**Comment by jfennick** [comment]
> Also solved it for us.

When can we expect a bugfix release?

**Comment by kevlened** [comment]
@jfennick @WP-LKL Unfortunately, no ETA. I can't access the email behind the pypi account anymore, so I can't push. I recommend version pinning an old pytest version.

https://github.com/pypa/pypi-support/issues/2343

**Comment by The-Compiler** [comment]
No need to pin, just add `py` to your dependencies manually.

**Pull request merged**
